### ISSUE TITLE
To add a Json file to save the details of Contact Us form

### ISSUE THREAD

**Issue by pooranjoyb** [devarshishimpi/stonecss#56]
**FEATURE**

I feel it would be great if we create a simple Database to track the records of people filling the Contact Us form.
It will enhance the project as it will have a simple DB to save data.

**SOLUTION**

The above mentioned can be achieved by accessing the contents of the Contact form using JS and writing them in the JSON file (as dictionaries)

I want to work in this issue for Hacktoberfest-2022. Would be glad if you assign this to me :) @devarshishimpi

**Comment by devarshishimpi** [comment]
Hi, This feature won't be worked on since we currently use Netlify Forms which handles form validation as well as saving all the records in the form of `.csv`

We can come back to this later again once we have released the framework and added docs instead of the landing page. This feature would be required at that moment.

**Comment by devarshishimpi** [comment]
You may create a new issue for the same later once the framework is released. I cannot guarantee that it will become a part of hacktoberfest as I don't think the framework is possible to be released this month.

**Comment by pooranjoyb** [comment]
Ok thanks letting me know. Will look into that for sure in the future.
